FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY nextjs-app/package*.json ./

# Install dependencies
RUN npm install
#RUN npm ci

# Copy the rest of the application
COPY nextjs-app ./

# Build the Next.js app
RUN npm run build

# Create a non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Expose the port
EXPOSE 3000
# Set environment variables
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Start the application
CMD ["npm", "start"]
