
catalog:
  default:
    uri: http://rest:8181
    type: rest
    s3.endpoint: http://minio:9000
    s3.access-key-id: admin
    s3.secret-access-key: password
    s3.path-style-access: true
    warehouse: s3://warehouse/
